#!/usr/bin/env python3
"""
SKiDL Netlist for test_board
Generated by PCB Design Agency - Netlist Agent
Date: 2025-10-04 23:00:43
"""

import os

# Set KiCad symbol directory for SKiDL
os.environ.setdefault("KICAD8_SYMBOL_DIR", r"C:\Program Files\KiCad\9.0\share\kicad\symbols")

from skidl import *

# Set default tool to KiCad
set_default_tool(KICAD8)

# Circuit name
circuit_name = 'test_board'

# Component definitions
# Each component is defined with its symbol and footprint
J1 = Part('Connector_Generic', 'Conn_01x02', ref='J1', footprint='Connector_JST:JST_PH_B2B-PH-K_1x02_P2.00mm_Vertical', value='JST')
D1 = Part('Device', 'LED', ref='D1', footprint='LED_SMD:LED_0805_2012Metric', value='Red')
R1 = Part('Device', 'R', ref='R1', footprint='Resistor_SMD:R_0805_2012Metric', value='220')

# Net definitions and connections
# Net: VCC
VCC = Net('VCC')
VCC += J1['1']
VCC += R1['1']

# Net: LED_A
LED_A = Net('LED_A')
LED_A += R1['2']
LED_A += D1['1']

# Net: GND
GND = Net('GND')
GND += D1['2']
GND += J1['2']

# Run Electrical Rule Check
ERC()

# Generate netlist
generate_netlist()

print('[OK] Netlist generated successfully')